config/routes.rb
Rails.application.routes.draw do
  resources :cats
end

app/models/cat.rb
class Cat < ActiveRecord::Base

  COLORS = ["white", "black", "brown", "orange", "tortoiseshell",
    "tuxedo", "tabby", "siamese", "gray", "tan"]

  validates :birth_date, :name, presence: true
  validates :color, presence: true, inclusion: { in: COLORS}
  validates :sex, presence: true, length: { maximum: 1 },
            inclusion: { in: ['M', 'F'] }

  def age
    cat_age = Date.today.year - birth_date.year
  end

  def inspect
    sex == "M" ? cat_pronoun = "he" : cat_pronoun = "she"
    sex == "M" ? pos_pronoun = "his" : pos_pronoun = "her"
    output = "#{name} the cat! #{pos_pronoun.titlecase} color is #{color}, and #{cat_pronoun} was born on #{birth_date}!!!"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def create
    @cat = Cat.create!(cat_params)
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    @cat.update_attributes(cat_params)
    render :show
  end


  private

  def cat_params
    params.require(:cat).permit(:name, :color, :sex, :birth_date, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% http_method = (@cat.persisted? ? "patch" : "post") %>
<% @cat.persisted? ? url_method = cat_url(@cat) : url_method = cats_url %>

<form action="<%=url_method%>" method="post">

  <input type="hidden" name="_method" value="<%= http_method %>">

  <label for="cat_name">Cat Name</label>
  <input type="text" id="cat_name" name="cat[name]" value="<%=@cat.name%>">

  <br><br>
  <%female = @cat.sex == "F"%>
  <input type="radio" name="cat[sex]" id = "cat_sex_female" value="F"
  <%="checked" if female%>>
  <label for="cat_sex_female">Female</label>
  <br>
  <input type="radio" name="cat[sex]" id = "cat_sex_male" value="M"
  <%="checked" unless female%>>
  <label for="cat_sex_male">Male</label>


  <br><br>

  <label for="cat_color">Color of cat</label>
  <select name="cat[color]" id="cat_color">
    <option selected><%=@cat.color%></option>
    <% Cat::COLORS.each do |color| %>
      <option value="<%=color%>"><%=color.titlecase%></option>
    <%end%>
  </select>

  <br><br>

  <label for="cat_birthday">Cat's birthday</label>
  <input type="date" id="cat_birthday" name="cat[birth_date]" value="<%=@cat.birth_date%>">

  <br><br>

  <label for="cat_description">Tell us about your cat</label>
  <input type="textarea" id="cat_description" name="cat[description]" value="<%=@cat.description%>">

  <br><br>

<input type="submit" value="Update cat!">
</form>

app/views/cats/edit.html.erb
<h2>LET'S EDIT A CAT!!!</h2>

<%=render "form", cat: @cat, action: :edit%>

app/views/cats/index.html.erb
<h2>Cats</h2>

<ul>
  <% @cats.each do |cat| %>
    <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
  <% end %>
</ul>

<%= link_to "Create new cat!", new_cat_url %>

app/views/cats/new.html.erb
<h2>LET'S MAKE A CAT!!!</h2>

<%=render "form", cat: @cat, action: :new%>

app/views/cats/show.html.erb
<!DOCTYPE html>

<html>

<h2><%= "#{@cat.name}!!" %></h2>

<body>

<table>
  <tr>
      <td><strong>Sex</strong></td>
      <td><strong>Age</strong></td>
      <td><strong>Color</strong></td>
      <td><strong>Description</strong></td>
  </tr>
  <tr>
      <td><%=@cat.sex%></td>
      <td><%=@cat.age%></td>
      <td><%=@cat.color%></td>
      <td><%=@cat.description%></td>
  </tr>

</table>

<br><br>

<a href="<%=edit_cat_url(@cat)%>">Edit this cat!</a>

<!-- <a href"<%#=destroy_cat_url%>">Remove cat from the database.</a> -->

<br><br>
<a href="<%=cats_url%>">Back to index.</a>

</body>

</html>

app/views/cats/stuff.html.erb
<form action="<%= cats_url %>" method="post">

  <label for="cat_name">Cat Name</label>
  <input type="text" id="cat_name" name="cat[name]">

<br><br>


  <input type="radio" name="cat[sex]" id = "cat_sex_female" value="F">
  <label for="cat_sex_female">Female</label>
  <br>
  <input type="radio" name="cat[sex]" id = "cat_sex_male" value="M">
  <label for="cat_sex_male">Male</label>


<br><br>

  <label for="cat_color">Color of cat</label>
  <select name="cat[color]" id="cat_color">
    <option selected>Choose a color</option>
    <% Cat::COLORS.each do |color| %>
      <option value="<%=color%>"><%=color.titlecase%></option>
    <%end%>
  </select>

<br><br>

  <label for="cat_birthday">Cat's birthday</label>
  <input type="date" id="cat_birthday" name="cat[birth_date]">

<br><br>

  <label for="cat_description">Tell us about your cat</label>
  <input type="textarea" id="cat_description" name="cat[description]">

<br><br>

<input type="submit" value="Create cat!">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>